name: Run Tests

on:
  push:
    branches:
      - main
      - dev
      - tests
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET}}
      JWT_LIFETIME: ${{ secrets.JWT_LIFETIME}}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: usando node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: run install
        run: npm install
      - name: run test
        run: npm run test
